### ISSUE TITLE
Orange highlight in tab nav is wider than the button

### ISSUE THREAD

**Issue by david-gauquelin** [ethersphere/gateway#39] opened 2021-06-18 12:32 UTC
<img width="477" alt="Screenshot 2021-06-18 at 14 31 22" src="https://user-images.githubusercontent.com/46993354/122561274-f661fa80-d041-11eb-853a-52ae9b98ba11.png">

**Comment by vojtechsimetka** [comment] 2021-07-04 22:00
closed as a duplicate of #78

**Closed by vojtechsimetka** 2021-07-04 22:00 UTC
Labels: issue
